## Site Meta ##
# The title of the website.
title: "李宸铭摄影"
# The description of the website
description: "李宸铭的摄影作品集"
# Keywords/tags for you site.
keywords: "lens, jeykll-lens, jekyll, theme, jekyll-theme, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: "Copyright &copy; 2017 - Elastic Designs."

## Site Configurations ##
# 1st heading of the site.
header: "李宸铭"
# 2nd heading/sub heading of the website.
subheader: "摄影作品"
# A description/bio of the website.
bio: "热爱摄影的高中生，喜欢捕捉光影的瞬间"
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: "lcm081216-rgb"
  # Your email address.
  email: "180578790@qq.com"

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
